#!/usr/bin/env python
import os
from tardisatomic import construct_atom_db
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('dbname')
parser.add_argument('--gfall',help='Specify which gfall database the script should use. If nothing is given the script tries to take the default "__file__/data/gfall.db".',type=str,default=None)

args = parser.parse_args()



#select_atoms = (6, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30)

os.system('rm %s' % args.dbname)
conn = construct_atom_db.new_linelist_from_gfall(args.dbname,gfall_fname=args.gfall)
conn = construct_atom_db.create_levels(conn)
conn = construct_atom_db.link_levels(conn)
conn.commit()

conn.close()
