#!/usr/bin/env python
import os
from tardisatomic import construct_atom_db
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('dbname')
parser.add_argument('gfall',help='Specify which gfall database the script should use.')
args = parser.parse_args()

if os.exists(args.dbname):
    if raw_input('{0} does exist. Overwrite [y/N]'.format(args.dbname)).lower().strip() == 'y':
        os.system('rm {0}'.format(args.dbname))
    else:
        raise IOError('{0} exists -- aborting'.format(args.dbname))

conn = construct_atom_db.new_linelist_from_gfall(args.dbname,gfall_fname=args.gfall)
conn = construct_atom_db.create_levels(conn)
conn = construct_atom_db.link_levels(conn)
conn = construct_atom_db.ion_xs(conn)
construct_atom_db.add_artificial_ionized_levels(conn)
conn.commit()

conn.close()
